version: '2'
services:
    postgres:
        image: "appiriodevops/submissions:postgres"
        environment:
            POSTGRES_PASSWORD: "test"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "test"
        ports:
            - "5432:5432"
    sqs:
        image: "appiriodevops/submissions:sqs"
        ports:
            - "4568:4568"
    aws-init:
        image: "appiriodevops/submissions:aws-cli"
        environment:
            IP: "$DOCKER_IP"
        depends_on:
            - sqs
        command: "/bin/bash -c /data/init.sh"
    informix:
        image: appiriodevops/informix:1.2
        ports:
            - "2021:2021"
    mock-services:
        image: appiriodevops/submissions:mock-services
        environment:
            BASE_URL: "http://$DOCKER_IP"
        ports:
            - "8080:8080"
    kafka:
        image: spotify/kafka
        environment:
            ADVERTISED_HOST: $DOCKER_IP
            ADVERTISED_PORT: 9092
        ports:
            - "2181:2181"
            - "9092:9092"
    nginx:
        image: appiriodevops/submissions:nginx-1.0
        depends_on:
            - aws-init
            - mock-services
        environment:
            DOCKER_IP: $DOCKER_IP
            HOST_IP: $HOST_IP
        ports:
            - "80:80"
    submissions:
        image: appiriodevops/submissions:frontend-1.0
        depends_on:
            - nginx
            - informix
            - kafka
            - postgres
        ports:
            - "3000:3000"
